## Copyright (c) 2026, Ernest Benedict and contributors
## For license information, please see license.txt

from frappe import _


def execute(filters=None):
    ## Get column definitions from report structure
    columns = get_columns()
    
    ## Fetch and format data
    data = get_static_data()
    
    return columns, data


def get_columns():
    ## Define all report columns with labels, field names, types and widths
    return [
        {"label": _("SECTION"), "fieldname": "section", "fieldtype": "Data", "width": 120},
        {"label": _("CATEGORY"), "fieldname": "category", "fieldtype": "Data", "width": 120},
        {"label": _("APPLIED WEIGHT"), "fieldname": "dispatch_ratio_pct", "fieldtype": "Percent", "width": 120},
        {"label": _("ACHIEVEMENT"), "fieldname": "dispatch_value_achievement", "fieldtype": "Currency", "width": 145},
        {"label": _("TARGET VALUE"), "fieldname": "dispatch_value_target", "fieldtype": "Currency", "width": 145},
        {"label": _("% ACHIEVED"), "fieldname": "dispatch_value_pct", "fieldtype": "Percent", "width": 120},
        {"label": _("APPLIED WEIGHT SCORE"), "fieldname": "dispatch_value_weighted", "fieldtype": "Float", "precision": 2, "width": 150},
        {"label": _("ACHIEVEMENT"), "fieldname": "lead_time_achievement", "fieldtype": "Int", "width": 125},
        {"label": _("TARGET ORDERS"), "fieldname": "lead_time_target", "fieldtype": "Int", "width": 135},
        {"label": _("% ACHIEVED"), "fieldname": "lead_time_pct", "fieldtype": "Percent", "width": 120},
        {"label": _("APPLIED WEIGHT SCORE"), "fieldname": "lead_time_weighted", "fieldtype": "Float", "precision": 2, "width": 150},
        {"label": _("AVERAGE ACHIEVED WEIGHT AT 43%"), "fieldname": "dispatch_avg_weighted", "fieldtype": "Float", "precision": 2, "width": 190},
        {"label": _("APPLIED WEIGHT"), "fieldname": "picking_ratio_pct", "fieldtype": "Percent", "width": 120},
        {"label": _("ACHIEVEMENT"), "fieldname": "picking_orders_achievement", "fieldtype": "Int", "width": 125},
        {"label": _("TARGET ORDERS"), "fieldname": "picking_orders_target", "fieldtype": "Int", "width": 135},
        {"label": _("% ACHIEVED"), "fieldname": "picking_orders_pct", "fieldtype": "Percent", "width": 120},
        {"label": _("APPLIED WEIGHT SCORE"), "fieldname": "picking_orders_weighted", "fieldtype": "Float", "precision": 2, "width": 150},
        {"label": _("ACHIEVEMENT QTY"), "fieldname": "picking_qty_achievement", "fieldtype": "Float", "precision": 2, "width": 140},
        {"label": _("TARGET QTY"), "fieldname": "picking_qty_target", "fieldtype": "Float", "precision": 2, "width": 120},
        {"label": _("% ACHIEVED"), "fieldname": "picking_qty_pct", "fieldtype": "Percent", "width": 120},
        {"label": _("APPLIED WEIGHT SCORE"), "fieldname": "picking_qty_weighted", "fieldtype": "Float", "precision": 2, "width": 150},
        {"label": _("ACHIEVEMENT VALUE"), "fieldname": "picking_value_achievement", "fieldtype": "Currency", "width": 150},
        {"label": _("TARGET VALUE"), "fieldname": "picking_value_target", "fieldtype": "Currency", "width": 145},
        {"label": _("% ACHIEVED"), "fieldname": "picking_value_pct", "fieldtype": "Percent", "width": 120},
        {"label": _("APPLIED WEIGHT SCORE"), "fieldname": "picking_value_weighted", "fieldtype": "Float", "precision": 2, "width": 150},
        {"label": _("AVERAGE ACHIEVED WEIGHT AT 33%"), "fieldname": "picking_avg_weighted", "fieldtype": "Float", "precision": 2, "width": 190},
        {"label": _("APPLIED WEIGHT"), "fieldname": "packing_ratio_pct", "fieldtype": "Percent", "width": 120},
        {"label": _("ACHIEVEMENT"), "fieldname": "packing_orders_achievement", "fieldtype": "Int", "width": 125},
        {"label": _("TARGET ORDERS"), "fieldname": "packing_orders_target", "fieldtype": "Int", "width": 135},
        {"label": _("% ACHIEVED"), "fieldname": "packing_orders_pct", "fieldtype": "Percent", "width": 120},
        {"label": _("APPLIED WEIGHT SCORE"), "fieldname": "packing_orders_weighted", "fieldtype": "Float", "precision": 2, "width": 150},
        {"label": _("ACHIEVEMENT QTY"), "fieldname": "packing_qty_achievement", "fieldtype": "Float", "precision": 2, "width": 140},
        {"label": _("TARGET QTY"), "fieldname": "packing_qty_target", "fieldtype": "Float", "precision": 2, "width": 120},
        {"label": _("% ACHIEVED"), "fieldname": "packing_qty_pct", "fieldtype": "Percent", "width": 120},
        {"label": _("APPLIED WEIGHT SCORE"), "fieldname": "packing_qty_weighted", "fieldtype": "Float", "precision": 2, "width": 150},
        {"label": _("ACHIEVEMENT VALUE"), "fieldname": "packing_value_achievement", "fieldtype": "Currency", "width": 150},
        {"label": _("TARGET VALUE"), "fieldname": "packing_value_target", "fieldtype": "Currency", "width": 145},
        {"label": _("% ACHIEVED"), "fieldname": "packing_value_pct", "fieldtype": "Percent", "width": 120},
        {"label": _("APPLIED WEIGHT SCORE"), "fieldname": "packing_value_weighted", "fieldtype": "Float", "precision": 2, "width": 150},
        {"label": _("AVERAGE ACHIEVED WEIGHT AT 19%"), "fieldname": "packing_avg_weighted", "fieldtype": "Float", "precision": 2, "width": 190},
        {"label": _("APPLIED WEIGHT"), "fieldname": "location_ratio_pct", "fieldtype": "Percent", "width": 120},
        {"label": _("ACHIEVEMENT"), "fieldname": "location_achievement", "fieldtype": "Float", "precision": 2, "width": 130},
        {"label": _("TARGET LOCATION ACCURACY 15 LOCATIONS"), "fieldname": "location_target", "fieldtype": "Float", "precision": 2, "width": 225},
        {"label": _("% ACHIEVED"), "fieldname": "location_pct", "fieldtype": "Percent", "width": 120},
        {"label": _("APPLIED WEIGHT SCORE"), "fieldname": "location_weighted", "fieldtype": "Float", "precision": 2, "width": 150},
        {"label": _("TOTAL AVERAGE APPLIED WEIGHT % ACHIEVED IN 4 CATEGORIES"), "fieldname": "total_weighted_score", "fieldtype": "Float", "precision": 2, "width": 280},
        {"label": _("TOTAL AVERAGE APPLIED WEIGHT %"), "fieldname": "total_weighted_pct", "fieldtype": "Percent", "width": 190},
    ]


def get_static_data():
    ## Return performance data for all departments and categories
    return [
        {
            "section": "DISPATCH DEPT",
            "category": "CENTRAL",
            "dispatch_ratio_pct": 43,
            "dispatch_value_achievement": 253017857,
            "dispatch_value_target": 253017857,
            "dispatch_value_pct": 100,
            "dispatch_value_weighted": 0.43,
            "lead_time_achievement": 300,
            "lead_time_target": 300,
            "lead_time_pct": 100,
            "lead_time_weighted": 0.43,
            "dispatch_avg_weighted": 0.43,
            "picking_ratio_pct": 33,
            "picking_orders_achievement": 20,
            "picking_orders_target": 28,
            "picking_orders_pct": 71.43,
            "picking_orders_weighted": 0.24,
            "picking_qty_achievement": 2000,
            "picking_qty_target": 2486,
            "picking_qty_pct": 80.45,
            "picking_qty_weighted": 0.27,
            "picking_value_achievement": 30000000,
            "picking_value_target": 36900000,
            "picking_value_pct": 81.30,
            "picking_value_weighted": 0.27,
            "picking_avg_weighted": 0.26,
            "packing_ratio_pct": 19,
            "packing_orders_achievement": 45,
            "packing_orders_target": 48,
            "packing_orders_pct": 93.75,
            "packing_orders_weighted": 0.18,
            "packing_qty_achievement": 2000,
            "packing_qty_target": 2097,
            "packing_qty_pct": 95.37,
            "packing_qty_weighted": 0.18,
            "packing_value_achievement": 31000000,
            "packing_value_target": 31132933,
            "packing_value_pct": 99.57,
            "packing_value_weighted": 0.19,
            "packing_avg_weighted": 0.18,
            "location_ratio_pct": 5,
            "location_achievement": 10,
            "location_target": 15,
            "location_pct": 66.67,
            "location_weighted": 0.03,
            "total_weighted_score": 0.90,
            "total_weighted_pct": 90,
        },
        {
            "section": "DISPATCH DEPT",
            "category": "UP COUNTRY",
            "dispatch_ratio_pct": 43,
            "dispatch_value_achievement": 500000000,
            "dispatch_value_target": 561006469,
            "dispatch_value_pct": 89.13,
            "dispatch_value_weighted": 0.38,
            "lead_time_achievement": 400,
            "lead_time_target": 460,
            "lead_time_pct": 86.96,
            "lead_time_weighted": 0.37,
            "dispatch_avg_weighted": 0.38,
            "picking_ratio_pct": 33,
            "picking_orders_achievement": 57,
            "picking_orders_target": 57,
            "picking_orders_pct": 100,
            "picking_orders_weighted": 0.33,
            "picking_qty_achievement": 3000,
            "picking_qty_target": 4972,
            "picking_qty_pct": 60.34,
            "picking_qty_weighted": 0.20,
            "picking_value_achievement": 70000000,
            "picking_value_target": 73800000,
            "picking_value_pct": 94.85,
            "picking_value_weighted": 0.31,
            "picking_avg_weighted": 0.28,
            "packing_ratio_pct": 19,
            "packing_orders_achievement": 20,
            "packing_orders_target": 24,
            "packing_orders_pct": 83.33,
            "packing_orders_weighted": 0.16,
            "packing_qty_achievement": 3000,
            "packing_qty_target": 4195,
            "packing_qty_pct": 71.51,
            "packing_qty_weighted": 0.14,
            "packing_value_achievement": 55000000,
            "packing_value_target": 62265866,
            "packing_value_pct": 88.33,
            "packing_value_weighted": 0.17,
            "packing_avg_weighted": 0.15,
            "location_ratio_pct": 5,
            "location_achievement": 15,
            "location_target": 15,
            "location_pct": 100,
            "location_weighted": 0.05,
            "total_weighted_score": 0.86,
            "total_weighted_pct": 86,
        },
        {
            "section": "STORES EXECUTIVES",
            "category": "ALL STORES",
            "dispatch_ratio_pct": None,
            "dispatch_value_achievement": None,
            "dispatch_value_target": None,
            "dispatch_value_pct": None,
            "dispatch_value_weighted": None,
            "lead_time_achievement": None,
            "lead_time_target": None,
            "lead_time_pct": None,
            "lead_time_weighted": None,
            "dispatch_avg_weighted": None,
            "picking_ratio_pct": 59,
            "picking_orders_achievement": 100,
            "picking_orders_target": 113,
            "picking_orders_pct": 88.50,
            "picking_orders_weighted": 0.52,
            "picking_qty_achievement": 3000,
            "picking_qty_target": 9944,
            "picking_qty_pct": 30.17,
            "picking_qty_weighted": 0.18,
            "picking_value_achievement": 140000000,
            "picking_value_target": 147600000,
            "picking_value_pct": 94.85,
            "picking_value_weighted": 0.56,
            "picking_avg_weighted": 0.42,
            "packing_ratio_pct": 33,
            "packing_orders_achievement": 90,
            "packing_orders_target": 95,
            "packing_orders_pct": 94.74,
            "packing_orders_weighted": 0.31,
            "packing_qty_achievement": 5000,
            "packing_qty_target": 8390,
            "packing_qty_pct": 59.59,
            "packing_qty_weighted": 0.20,
            "packing_value_achievement": 188000000,
            "packing_value_target": 124531732,
            "packing_value_pct": 100,
            "packing_value_weighted": 0.50,
            "packing_avg_weighted": 0.34,
            "location_ratio_pct": 8,
            "location_achievement": 15,
            "location_target": 15,
            "location_pct": 100,
            "location_weighted": 0.08,
            "total_weighted_score": 0.84,
            "total_weighted_pct": 84,
        },
        {
            "section": "STORES EXECUTIVES",
            "category": "KEN",
            "dispatch_ratio_pct": None,
            "dispatch_value_achievement": None,
            "dispatch_value_target": None,
            "dispatch_value_pct": None,
            "dispatch_value_weighted": None,
            "lead_time_achievement": None,
            "lead_time_target": None,
            "lead_time_pct": None,
            "lead_time_weighted": None,
            "dispatch_avg_weighted": None,
            "picking_ratio_pct": 59,
            "picking_orders_achievement": 0,
            "picking_orders_target": 0,
            "picking_orders_pct": 0,
            "picking_orders_weighted": 0,
            "picking_qty_achievement": 0,
            "picking_qty_target": 0,
            "picking_qty_pct": 0,
            "picking_qty_weighted": 0,
            "picking_value_achievement": 0,
            "picking_value_target": 0,
            "picking_value_pct": 0,
            "picking_value_weighted": 0,
            "picking_avg_weighted": 0,
            "packing_ratio_pct": 33,
            "packing_orders_achievement": 50,
            "packing_orders_target": 95,
            "packing_orders_pct": 52.63,
            "packing_orders_weighted": 0.17,
            "packing_qty_achievement": 15000,
            "packing_qty_target": 8390,
            "packing_qty_pct": 100,
            "packing_qty_weighted": 0.59,
            "packing_value_achievement": 180000000,
            "packing_value_target": 124531732,
            "packing_value_pct": 100,
            "packing_value_weighted": 0.74,
            "packing_avg_weighted": 0.74,
            "location_ratio_pct": 8,
            "location_achievement": 10,
            "location_target": 15,
            "location_pct": 66.67,
            "location_weighted": 0.05,
            "total_weighted_score": 0.79,
            "total_weighted_pct": 79,
        },
        {
            "section": "STORES EXECUTIVES",
            "category": "FAHAD",
            "dispatch_ratio_pct": None,
            "dispatch_value_achievement": None,
            "dispatch_value_target": None,
            "dispatch_value_pct": None,
            "dispatch_value_weighted": None,
            "lead_time_achievement": None,
            "lead_time_target": None,
            "lead_time_pct": None,
            "lead_time_weighted": None,
            "dispatch_avg_weighted": None,
            "picking_ratio_pct": 59,
            "picking_orders_achievement": 0,
            "picking_orders_target": 0,
            "picking_orders_pct": 0,
            "picking_orders_weighted": 0,
            "picking_qty_achievement": 0,
            "picking_qty_target": 0,
            "picking_qty_pct": 0,
            "picking_qty_weighted": 0,
            "picking_value_achievement": 0,
            "picking_value_target": 0,
            "picking_value_pct": 0,
            "picking_value_weighted": 0,
            "picking_avg_weighted": 0,
            "packing_ratio_pct": 33,
            "packing_orders_achievement": 0,
            "packing_orders_target": 24,
            "packing_orders_pct": 0,
            "packing_orders_weighted": 0,
            "packing_qty_achievement": 2000,
            "packing_qty_target": 2097,
            "packing_qty_pct": 95.37,
            "packing_qty_weighted": 0.31,
            "packing_value_achievement": 30000000,
            "packing_value_target": 31132933,
            "packing_value_pct": 96.36,
            "packing_value_weighted": 0.43,
            "packing_avg_weighted": 0.43,
            "location_ratio_pct": 8,
            "location_achievement": 10,
            "location_target": 15,
            "location_pct": 66.66,
            "location_weighted": 0.05,
            "total_weighted_score": 0.48,
            "total_weighted_pct": 48,
        },
    ]